name: Automated GitHub Activity

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  commit-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install dependencies
        run: npm install

      - name: Run Commit Automation Script
        run: node commit.js

      - name: Run GitHub Activities Script
        run: node githubActivities.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
